# Python Review

Short review about some core concepts in python exemplified by objects in the numpy library

- recall basic python vocab
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files. 

**NumPy:**

- core library for numerical computing in Python
- many of the libraries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

let's import NumPy with its **standard abbreviation** `np`:

In [2]:
import numpy as np

## Variable

**variable:** a name we assign to a particular object in Python

note: esc + m changes code to markdown cell

Exp:

In [3]:
# Assign a small variable to a

a = np.array([ [1,1,2], [3,5,8] ])

To view a variable's valye from our jupyter notebook:

In [4]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: use `snake-case` for naming variables.

this is the convention we will use in the course. Why?
PEP 8 style guide for python code recommends snakecase.

**remember that variable names should be both descriptive and concise**

## Objects

**object:** (informally speaking) an object is a bundle of *properties* and *actions* about something specific.
If object is a df, then the properties are the number of rows, the names of the columns, and the date created. Actions oculd be selecting a specific row or adding a new column. 

A variable is the name we give a specific object, and the same object can be referenced by different variables

In practice, we can often use the word variable and object interchangeably. 

## Types

Every object in python has a **type**, the type tells us what kind of object we have. 
We can also call the type of an object, the **class** of an object. So class and object both mean what kind of object we have. 

In [6]:
print(a)

[[1 1 2]
 [3 5 8]]


In [7]:
# see the type/class of a variable/object by using the `type` function
type(a)

numpy.ndarray

The `numpy.ndarray` is the core object/data type of the NumPy package

In [8]:
print(a[0,0])

type(a[0,0])

1


numpy.int64

`numpy.int64` is not the standard Python integer type `int`.

`numpy.int64` is a special data type in NumPy telling us that 1 is an integer stored as a 64-bit number. 

Check-in: access the value 5 in array `a`.

In [11]:
a[1,1]

5

## Functions

`print` was our first example of a python **function**

Functions take in a set of **arguments**, separated by commas, and use those arguments to create an **output**.

In this course, we'll be using argument and parameter interchangeable, but they do have slightly different meanings. 

We can ask for information about what a function does by executing `?` followed by the function name

In [12]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtai nis called a **docstring**, a special type of comment that is used to document how a function (or a class, or module) works. 

Notice that there are different types of arguments inside the function's ()

Roughly speaking, a function has 2 types of arguments:
- **non-optional arguments**: arguments *you* have to specify for the function to work

-**optional arguments**: arguments that are pre filled with a default value by the function, but you can override the. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value`

exp:
`end` is a parameter in `print` with default valye a new line
we can pass the value `:-)` to this parameter so if finished the line with `:-)` 

In [13]:
print('Change the end parameter', end = ':-)')

Change the end parameter:-)

## Attributes and methods

An object in python has attributes and methods. 

- **attribute**: a property of the object, some piece of information about it. 
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object itself. 

## Check-in

Make a diagram like the cat one, for a class `fish`. What are its attributes and methods? (3)

Exp:
NumPy arrays have many methods and attributes. For exp:

In [14]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [15]:
# T is an example of an attribute, it returns the transpose of array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [17]:
type(a.T)

numpy.ndarray

In [19]:
# shape another attribute tells us the shape of the array
print(a.shape)

(2, 3)


In [20]:
print(type(a.shape))

<class 'tuple'>


In [21]:
# ndim is an attribute holding the number of array dimensions
print('dim:', a.ndim, '| type:', type(a.ndim))

dim: 2 | type: <class 'int'>


Attributes can have many different data types.

Some examples of methods. 

In [25]:
# The min method returns the minimum value in the array along a specified axis
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [27]:
# Run min method without axis- axis is optional
a.min()

1

Remember that methods are **functions** associated with an object. We can confirm this!

In [28]:
# method tolist() transforms array into a list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [30]:
type(a.tolist)

builtin_function_or_method

Exercise

1. Read the `print` function help. What is the type of argument `sep`? Is this a default or non-default? Why?

In [32]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



2. Create two new variables, one with the integer value 277 and the other with the string 99.
3. Use your variables to print 77%99%77 by changing the valye of one of the default argumentsin print. 

In [35]:
num = 77
string = '999'

In [37]:
print(num, string, num, sep= '%')

77%999%77
