# Python Review

Short review about some core concepts in python exemplified by objects in the numpy library

- recall basic python vocab
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files. 

**NumPy:**

- core library for numerical computing in Python
- many of the libraries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

let's import NumPy with its **standard abbreviation** `np`:

In [1]:
import numpy as np

## Variable

**variable:** a name we assign to a particular object in Python

note: esc + m changes code to markdown cell

Exp:

In [ ]:
# Assign a small variable to a

a = np.array([ [1,1,2], [3,5,8] ])

To view a variable's valye from our jupyter notebook:

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]
